### PR TITLE
Remove dead pools

### PR DESCRIPTION
**Pull request by ZedPea**
#### auspool.turtleco.in
Never loads, API has been down for 7 or more days.

#### etnchina.io/trtl
Backend appears down, website doesn't load correctly, API has been down for 6 or more days.

#### slowandsteady.fun
As above, API has been down for 5 or more days.

#### trtl.blockchainera.net
Website loads blank page, API has been down for 7 or more days.

#### trtl.cryptonight.nl
Backend appears down, website doesn't load correctly, API has been down for 7 or more days.

#### trtl.flashpool.club
Backend appears down, website doesn't load correctly, expired SSL certificate, API has been down for 7 or more days.

#### turtle.coolmining.club
Pool shut down.

### CODE REVIEW

**Comment by derp-derp-derp** [comment]
Thanks, Z. If some of these went down due to recent network and/or daemon issues should we give them some time to get things straightened out?

**Comment by ZedPea** [comment]
Sure, what would you say is an adequate time frame to give pools? I'll stick to that in future.

**Comment by RocksteadyTC** [comment]
7 days is about the line for me, personally, when classifying pool admins as either "hobbyist" or "professional". 


- If a pool admin can keep an eye on their daemon, and they have a basic amount of interaction in the chat with miners and other developers, I consider them doing this professionally. 

- If a pool is often on a forked chain, or their daemon says "Network: Last block seen X days ago", or they only show up in chat when a fork update takes them out, I consider them a hobbyist, or an absentee administrator. 


Typically, these durations of downtime don't span longer than a few hours for the pro pool admin. For the hobbyist admin, they typically span days, cost money to miners who don't know any better, and end up having very little continuity of support. 


I propose that we should come up with a clear set of qualifiers for the readme of the pool-json repository that says "If you fall into this category, given these params, you'll be given an 'inactive' status, and after X time, dropped from the list". This is fair, and is something that can be automated so we don't have to keep listing and delisting pools. So long as we do it manually we can be accused of favoritism, but if it is automated, that removes a manual process and gives us better fairness for what may just be a case of "newbie pool admin".

**Comment by derp-derp-derp** [comment]
That sounds great @RocksteadyTC - how would the automation work? I don't have experience with such an implementation.

**Comment by derp-derp-derp** [comment]
Would this be an external application that runs scheduled checks on the entire list, tracks each pool's status, and modifies a (new) status property for offending pools after 5 days of downtime to 'inactive' and/or removes the pool from the list completely after 7 days? And it somehow interfaces with GitHub with commit and push the changes as they're made?

**Comment by derp-derp-derp** [comment]
If none of these are backup, then I think we can at least merge this PR for now - agreed?

**Comment by ZedPea** [comment]
They all appear to still be down, yes.

**Pull request merged**
