### PR TITLE
add null value to cryptonote.social

### PR DESCRIPTION
**Pull request by Sajo8**
it's freaking annoying because we have to put it in a try/except (catch()) since we get a key error since apiLink is non existent. now we can just check if it's not null 

plz

### CODE REVIEW

**Comment by brandonlehmann** [comment]
```javascript
for (var i = 0; i < pools.length; i++)
{
  if (!pool[i].apiUrl) continue;
  var url = pool[i].apiUrl
}
```

**Comment by zpalmtree** [comment]
I believe this pool does actually have an API - I'm just not aware of the api link

**Comment by zpalmtree** [comment]
Also - there is no sensible way to parse an 'other' pool, so you can branch on the type anyway.

**Comment by derp-derp-derp** [comment]
I agree with @zpalmtree - closing.

**Comment by Sajo8** [comment]
okie

**Pull request closed without merging**
