### PR TITLE
support nodejs pools in a separate list

### PR DESCRIPTION
**Pull request by derp-derp-derp**
I'm open to idea on ways to better organize this. The one issue I see here is that url in the Forknote context is for the API, but the url for the Node.js pools is just the pool webpage.

### CODE REVIEW

**Comment by derp-derp-derp** [comment]
Maybe each entry should have separate properties for API URL and webpage URL?

**Comment by pypper** [comment]
I'm on the fence.

The issue with grouping them all together with separate API and web URLs is that without further metadata, you're not sure what kind of API you're talking to. So you'll need to as well add a `type` field or what-have-you to each object literal so the people pulling this JSON down know what API they're interacting with.

The format @derp-derp-derp has here solves that, but if we want to add more types in the future (if more pool projects are developed and deployed with their own APIs) it'll be a whole-nother tree of urls.
And yami's model + `type` annotations, opens up to supporting more different types than 2 with the same format rather than having an entirely separate sub-list.

**Comment by yamiM0NSTER** [comment]
After thinking about it I am in with pypper, it would look like that:
```
"atpool.party" : {
            "url" : "https://turtle.atpool.party/",
            "api" : "http://turtle-eu.atpool.party:8117/",
            "type" : "forknote"
},
```
With that there is no need for splitting.

**Comment by derp-derp-derp** [comment]
Nice, guys. What about taking it one step further, and making it easier to loop:
```
{
            "title" : "AtPool",
            "url" : "https://turtle.atpool.party/",
            "api" : "http://turtle-eu.atpool.party:8117/",
            "type" : "forknote"
},
```

**Comment by yamiM0NSTER** [comment]
I mean, if it's easier to use then why not.

**Comment by pypper** [comment]
100% on board with @derp-derp-derp . an object of keys is nicer for humans to look at, but more frustrating for machines than a list of objects.

**Comment by pypper** [comment]
ohhh yeah, that's the stuff.

zero objections to the new format, perhaps only adding documentation to the README about how new items should be added / what each field should contain.

**Pull request merged**
