### PR TITLE
Add new TRTL mining pool

### PR DESCRIPTION
**Pull request by nthon**
Hi there,

I add new trtl mining pool:
address: https://trtl.cryptomine.cx
api: https://trtl.cryptomine.cx/api
fee: 0.1
Email to miner is supported.

Please help me merge it.

Thanks for your help.

Hon

### CODE REVIEW

**Comment by DiscoTim** [comment]
3 things:

your pool should be after cryptohispano (alphabetical)
your name has an extra / on the end Cryptomine.cx/
your api needs the / on the end.

**Comment by nthon** [comment]
Hello @DiscoTim 

Thanks for your help!

I corrected it.

Help me merged, please!

Thank you!

Hon

**Comment by DiscoTim** [comment]
almost, now there is some extra white space after CryptoPool.space. the rest looks good.

**Comment by brandonlehmann** [comment]
I formatted

**Pull request merged**
