### PR TITLE
Fixes CryptoNote.social api link

### PR DESCRIPTION
**Pull request by andrewnk**

### CODE REVIEW

**Comment by derp-derp-derp** [comment]
For consistency-sake all API URLs should have a trailing slash. Although I am open to opinions as to whether we should allow this one since it's currently the only type "other", and I see that it doesn't function correctly with a trailing slash.

**Comment by andrewnk** [comment]
As you noticed, it doesn't work correctly with the trailing slash. I think the exception should be made for those categorized as "other". If you are hitting the api's for an "other" then you will most likely have to custom code for it as it won't necessarily follow other framework api's.

**Comment by brandonlehmann** [comment]
Actually... it does work with the trailing slash...

* https://cryptonote.social/pool/statistics/trtl returns the overall pool information
* https://cryptonote.social/pool/statistics/trtl/ starts down the path of USER information (you just don't have a user selected, so it displays empty values)
* https://cryptonote.social/pool/statistics/trtl/iburnmycd shows my stats

**Comment by brandonlehmann** [comment]
That being said, perhaps we can hit up the cryptonote social guys such that with and without the trailing slash returns the pool stats? That might be quick enough for them to do :)

**Comment by cryptonote-social** [comment]
It should be possible without too much trouble I would think.   I can look into it later today.

**Comment by brandonlehmann** [comment]
Thanks!

**Comment by andrewnk** [comment]
Thanks!

**Comment by cryptonote-social** [comment]
This is fixed on my end now (I think ... let me know if you have issues)

**Comment by andrewnk** [comment]
Looks good! Thanks again everyone!

**Pull request closed without merging**
