### PR TITLE
adding new pool https://cryptonote.social/trtl

### PR DESCRIPTION
**Pull request by cryptonote-social**
adding my trtl pool to the list...

### CODE REVIEW

**Comment by yamiM0NSTER** [comment]
Please fix indentation and follow guidelines that are in Readme.md:
> Please add your pool to the list in alphabetical order, named using CamelCase.domain style, and including trailing slashes for the url and api values.

**Comment by RocksteadyTC** [comment]
Beat me to it, quick-draw-yami

**Comment by yamiM0NSTER** [comment]
Well my trap card was activated! Your move.

**Comment by cryptonote-social** [comment]
Thx and sorry to not have RTFM :)   What's with the trailing slash requirement though?  The URLs are correct without them.

**Comment by cryptonote-social** [comment]
OK, I should probably just leave out the API URL for now since it's not a complete API implementation at the moment. Is it OK to leave the API unspecified?

The site appropriately redirects for the site home URL so I can add a slash to that one.

**Comment by derp-derp-derp** [comment]
Thanks for merging this @RocksteadyTC - I didn't know what purpose listing it would serve if it wasn't a forknote or Node.js pool, but I should've commented sooner instead of leaving it sit.

**Pull request merged**
